server:
  port: 9001
  
spring:
  application:
    name: USER-REGISTERATION
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/register
    username: root
    password: 123412

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
       

      
      