server:
  port: 9191
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-REGISTERATION
          uri: lb://USER-REGISTERATION
          predicates:
            - Path=/user/**
        
      